Guanyung add device programmer subsystem stub
os-fpga/FOEDAG pull request #1021
Opened 2023-03-06 03:40 UTC by guanyung-rs

> ### Motivate of the pull request
> - [ ] To address an existing issue. If so, please provide a link to the issue: <issue id>
> - [x] Breaking new feature. If so, please describe the details in the description part.

> ### Describe the technical details
Created stub code for device programming subsystem
- Added DeviceProgrammer.cpp and header file to support following tcl commands
  - program, load_bitstream_file, verify
- Added ProgramDevice method for customization of the device programming flow

> #### What is currently done? (Provide issue link if applicable)
> 
> 
> 
> 
> 
>
> #### What does this pull request change?
> 
> 
> 
> 
> 

> ### Which part of the code base require a change
> 
> - [ ] Library: <Specify the library name>
> - [ ] Plug-in: <Specify the plugin name>
> - [x] Engine
> - [ ] Documentation
> - [ ] Regression tests
> - [ ] Continous Integration (CI) scripts

> ### Impact of the pull request

> - [ ] Require a change on Quality of Results (QoR)
> - [ ] Break back-compatibility. If so, please list who may be influenced.

2023-03-06 18:13 UTC, ravic-rs commented
1. Needs a dummy batch tcl test/script with these functions.
2. Test plan for all repositories including verification of device programming in CI (likely in upstream repositories).

2023-03-07 06:50 UTC, guanyung-rs commented
> 1. Needs a dummy batch tcl test/script with these functions.
> 2. Test plan for all repositories including verification of device programming in CI (likely in upstream repositories).

For #1, I added `program` tcl command into tests/TestGui/compiler_flow.tcl as part of testing

2023-03-07 09:36 UTC, ravic-rs commented on src/Compiler/CompilerDefines.h
> +static constexpr const char *PROGRAMDEVICE_LOG{"PROGRAMDEVICE.rpt"};
Remove this line, it's only for piping backend generated logs/std to a log file we display in GUI.

2023-03-07 09:42 UTC, ravic-rs commented on tests/TestGui/compiler_flow.tcl
> +program
program_device

2023-03-07 15:22 UTC, ravic-rs requested changes
Some conflicts needs to be resolved due to recent merges in same files.

2023-03-07 23:28 UTC, alain-rs commented
@chungshien please resolve the conflicts so we can merge this PR.

2023-03-08 00:38 UTC, guanyung-rs commented on src/Compiler/Compiler.cpp
> +  m_DesignQuery->RegisterCommands(interp, batchMode);
This is redundant. Line 430 and 432 is the doing the same thing.

2023-03-08 00:44 UTC, chungshien commented
@alain-rs - done. Had helped the team resolve the merge conflicts

@guanyung-rs - please double check when you are online and have time

But to be done, I am not sure I like the way the implementation is done. 
Currently it just "mimic" how designquery feature (GUI centric) is done and replicate the same for DeviceProgrammer. 

However DeviceProgrammer is not GUI feature, it is backend engine + command line executable support. The implementation include unnecessary dependencies/libraries that DeviceProgrammer does not need.

To me, this is not a clean implementation - a clean coding should only include the needed dependencies (header, library, etc).

2023-03-08 00:52 UTC, chungshien commented
The windows fail with "D:\a\FOEDAG\FOEDAG\src\DesignRuns\..\..\src\DesignQuery/DesignQuery.h(31): fatal error C1083: Cannot open include file: 'nlohmann_json/json.hpp': No such file or directory"

But I do not change (add or delete or modify) anything that related to designquerry.  

@guanyung-rs  can you double check if the current changelist is exact your original implement after I fix the conflict?

2023-03-08 00:58 UTC, guanyung-rs commented
> The windows fail with "D:\a\FOEDAG\FOEDAG\src\DesignRuns....\src\DesignQuery/DesignQuery.h(31): fatal error C1083: Cannot open include file: 'nlohmann_json/json.hpp': No such file or directory"
> 
> But I do not change (add or delete or modify) anything that related to designquerry.
> 
> @guanyung-rs can you double check if the current changelist is exact your original implement after I fix the conflict?

I am looking into the build issue in MSVC.

2023-03-08 02:31 UTC, guanyung-rs commented
@ravic-rs, FYA, the CI build checks have passed. Please review.

2023-03-08 03:17 UTC, alain-rs commented
The GUI needs a proxy (This subsystem) for the actual job done by a separate executable "Device programmer".
On the GUI side, this initial PR seems OK.

2023-03-08 03:17 UTC, merged