Use gtest framework for Configuration subsystem
os-fpga/FOEDAG pull request #1055
Opened 2023-04-10 05:18 UTC by guanyung-rs

> ### Motivate of the pull request
> - [ ] To address an existing issue. If so, please provide a link to the issue: <issue id>
> - [ ] Breaking new feature. If so, please describe details in the description part.
Follow up work from this PR https://github.com/os-fpga/FOEDAG/pull/1049
Use google test framework for Configuration subsystem tests

> ### Describe the technical details
> #### What is currently done? (Provide issue link if applicable)
> 
> 
> 
> 
> 
>
> #### What does this pull request change?
> 
> 
> 
> 
> 

> ### Which part of the code base require a change
> 
> - [ ] Library: <Specify the library name>
> - [ ] Plug-in: <Specify the plugin name>
> - [ ] Engine
> - [ ] Documentation
> - [ ] Regression tests
> - [ ] Continous Integration (CI) scripts

> ### Impact of the pull request

> - [ ] Require a change on Quality of Results (QoR)
> - [ ] Break back-compatibility. If so, please list who may be influenced.

2023-04-10 11:37 UTC, KochynVolodymyr commented on src/Configuration/CFGCommon/Test/CFGCommon_test.cpp
> +#include <gtest/gtest.h>
We have another folder for the unit tests: `tests/unittest/`

2023-04-10 11:37 UTC, KochynVolodymyr commented on src/Configuration/CFGCompiler/Test/CFGCompiler_test.cpp
> +Copyright 2023 The Foedag team
We have another folder for the unit tests: `tests/unittest/`

2023-04-10 17:53 UTC, ravic-rs requested changes
@guanyung-rs as mentioned in previous PR, please move the gtests to 
https://github.com/os-fpga/FOEDAG/tree/main/tests/unittest

2023-04-11 00:30 UTC, guanyung-rs commented
Ok. I will move them to the tests/unittest folder

2023-04-20 06:20 UTC, closed without merging