[RG-459] Initial implementation of IP Dialog box
os-fpga/FOEDAG pull request #1256
Opened 2023-08-31 19:51 UTC by KochynVolodymyr

### Motivate of the pull request
 - [ ] To address an existing issue. If so, please provide a link to the issue: <issue id>
 - [x] Breaking new feature. If so, please describe details in the description part.

 ### Describe the technical details
![image](https://github.com/os-fpga/FOEDAG/assets/95262932/7f3c176a-7942-40fe-9740-55767fdc47dc)

 ### Which part of the code base require a change
 
 - [x] Library: ipgenerate, ipconfigurator, foedagcore
 - [ ] Plug-in: <Specify the plugin name>
 - [ ] Engine
 - [ ] Documentation
 - [ ] Regression tests
 - [ ] Continous Integration (CI) scripts

2023-08-31 19:54 UTC, KochynVolodymyr commented on src/IpConfigurator/IPDialogBox.cpp
> +  setWindowTitle("IP Configuration");
@ravic-rs here is the title

2023-08-31 21:03 UTC, ravic-rs commented on src/IpConfigurator/IPDialogBox.cpp
> +  setWindowTitle("IP Configuration");
I made the change, thanks!

2023-09-01 19:42 UTC, ravic-rs requested changes
Requires error handling check for atleast IP location action. Others seems to be ok.

2023-09-01 21:55 UTC, KochynVolodymyr commented
> Requires error handling check for atleast IP location action. Others seems to be ok.

Done

2023-09-02 01:24 UTC, ravic-rs approved these changes

2023-09-02 01:31 UTC, merged