Adding command to validate pre and post synthesis ports
os-fpga/FOEDAG pull request #1299
Opened 2023-09-18 07:27 UTC by behzadmehmood-rs

> ### Motivate of the pull request
> - [ ] To address an existing issue. If so, please provide a link to the issue: <issue id>
> - [ x] Breaking new feature. If so, please describe details in the description part.

> ### Describe the technical details
Adding a command to validate pre and post synthesis ports.
> #### What is currently done? (Provide issue link if applicable)
> 
> 
> 
> 
> 
>
Currently, there is no command to check if the ports are same before and after synthesis.

> #### What does this pull request change?
> 
> 
> 
> 
> 
Now the ports of the synthesized netlist will be compared to the RTL ports. In case of a missing port after synthesis, an error will be generated and in case of an addition of new port, a warning will be issued.

> ### Which part of the code base require a change
> 
> - [ ] Library: <Specify the library name>
> - [ ] Plug-in: <Specify the plugin name>
> - [ ] Engine
> - [ ] Documentation
> - [ ] Regression tests
> - [ ] Continous Integration (CI) scripts

> ### Impact of the pull request

> - [ ] Require a change on Quality of Results (QoR)
> - [ ] Break back-compatibility. If so, please list who may be influenced.

2023-09-18 20:03 UTC, ravic-rs commented on src/Compiler/Compiler.cpp
> +    compiler->ErrorMessage("Error: Error in verify_synth_ports");
Remove the prepend here.

2023-09-18 20:05 UTC, ravic-rs commented on src/Compiler/Compiler.cpp
> +  int systemRet = std::system(command.c_str());
Please use "ExecuteAndMonitorSystemCommand" function here.

2023-09-18 20:06 UTC, ravic-rs requested changes
Atleast 2 comments to review.

2023-09-19 18:26 UTC, ravic-rs commented
@behzadmehmood-rs did you get a chance to review the comments ?

2023-09-19 18:36 UTC, behzadmehmood-rs commented
> @behzadmehmood-rs did you get a chance to review the comments ?

@ravic-rs  I could not work today due to some health issues, I will make changes tomorrow.

2023-09-20 06:11 UTC, behzadmehmood-rs commented on src/Compiler/Compiler.cpp
> +    compiler->ErrorMessage("Error: Error in verify_synth_ports");
Done.

2023-09-20 06:11 UTC, behzadmehmood-rs commented on src/Compiler/Compiler.cpp
> +  int systemRet = std::system(command.c_str());
Done.

2023-09-20 17:41 UTC, ravic-rs approved these changes

2023-09-20 17:42 UTC, merged