Update Pin Location Assign Method, replace `free` with `pin_constraint_disabled`
os-fpga/FOEDAG pull request #1378
Opened 2023-11-14 22:35 UTC by KochynVolodymyr

### Motivate of the pull request
 - [x] To address an existing issue. If so, please provide a link to the issue: EDA-2250
 - [ ] Breaking new feature. If so, please describe details in the description part.

 ### Describe the technical details
Update Pin Location Assign Method:
![image](https://github.com/os-fpga/FOEDAG/assets/95262932/77fe8907-924e-48cb-bf88-9f56158c3b25)
![image](https://github.com/os-fpga/FOEDAG/assets/95262932/14e33e8c-499c-47ff-b8f4-2b573c30989e)
![image](https://github.com/os-fpga/FOEDAG/assets/95262932/063b81bf-4ec4-4e58-ba32-17d83d8ef696)

 ### Which part of the code base require a change
 
 - [x] Library: compiler, foedagcore, newproject, projnavigator
 - [ ] Plug-in: <Specify the plugin name>
 - [ ] Engine
 - [ ] Documentation
 - [ ] Regression tests
 - [ ] Continous Integration (CI) scripts

2023-11-14 22:49 UTC, ravic-rs commented on src/Main/Tasks.cpp
> +    {FOEDAG::Compiler::PinAssignOpt::Free, "pin_constraint_disabled"}};
Shouldn't we change PinAssignOpt too ?

2023-11-14 22:49 UTC, ravic-rs reviewed
1 comment to resolve

2023-11-14 23:25 UTC, alain-rs requested changes
The Tcl command need to be able to accept both options (free and pin_constraint_disabled) and do the same thing as "free".
I don't see a change of the Tcl command parser.

2023-11-15 04:53 UTC, KochynVolodymyr commented
> The Tcl command need to be able to accept both options (free and pin_constraint_disabled) and do the same thing as "free". I don't see a change of the Tcl command parser.

@alain-rs we support both options:
![image](https://github.com/os-fpga/FOEDAG/assets/95262932/12be5e8f-6ac4-47e1-bc57-50b4d0904a34)

2023-11-15 04:56 UTC, alain-rs approved these changes

2023-11-15 04:56 UTC, merged