IPA codebase synchronization
os-fpga/FOEDAG pull request #1591
Opened 2024-05-17 11:31 UTC by w0lek

This PR contains IPA code synchronization with Aurora, and aggregates several tickets: feature, bugfix and code refactoring.

Changelog:
- IPA new way of parsing the VPR timing report based on attached report metadata. This feature is requred to work together with the VPR IPA functionality. 
- ReportModelLoader perform all heavy load in separate thread to not block the UI thread.
- Fix bug of slow critical path element selection with huge number of sub path elements (~10.000 elements produce delay about 8 seconds in past)
- IPA VIewer now has busy indicator while heavy work in process.
- Different code refactor enhancements.

2024-05-17 11:38 UTC, w0lek commented
@ravikiranchollangi @volodymyrkochyn 
I put PR to draft mode, to block merging PR.
But PR is actually ready for review, i don't plan to make any other fixes, except some which you may ask me to correct after reviewing it.

2024-05-17 15:30 UTC, ravikiranchollangi commented
> @ravikiranchollangi @volodymyrkochyn 
> 
> I put PR to draft mode, to block merging PR.
> 
> But PR is actually ready for review, i don't plan to make any other fixes, except some which you may ask me to correct after reviewing it.

For formatting use this:
.github/bin/run-clang-format.sh

There's also windows ci failure.

2024-05-22 15:00 UTC, w0lek commented
@ravikiranchollangi @volodymyrkochyn
CI stages looks all passed

2024-05-22 19:07 UTC, volodymyrkochyn commented on src/InteractivePathAnalysis/NCriticalPathWidget.cpp
> +#include "../Compiler/QLSettingsManager.h"
I don't see this file in the list. It looks like build will be broken with this flag.

2024-05-22 19:11 UTC, volodymyrkochyn commented on src/InteractivePathAnalysis/NCriticalPathWidget.cpp
> +#include "../Compiler/QLSettingsManager.h"
Closing this.

2024-05-22 19:27 UTC, ravikiranchollangi requested changes
Blocking this for logger discussion plus we have an ongoing release to add this now.

2024-05-28 16:47 UTC, ravikiranchollangi commented
> Blocking this for logger discussion plus we have an ongoing release to add this now.

Need to move the IPA log file to timing analysis task.

2024-06-04 14:39 UTC, w0lek commented
> > Blocking this for logger discussion plus we have an ongoing release to add this now.
> 
> Need to move the IPA log file to timing analysis task.

corrected here
https://github.com/os-fpga/FOEDAG/pull/1591/commits/7ca2411a95edbd9fb8575506303c349c7e3cfd4c

@volodymyrkochyn may you please review that change, is it ok?

2024-06-07 17:16 UTC, volodymyrkochyn commented
@w0lek looks good to me

2024-06-10 18:43 UTC, ravikiranchollangi approved these changes

2024-06-10 18:43 UTC, merged