hide menu bar on welcome page
os-fpga/FOEDAG pull request #623
Opened 2022-09-05 14:23 UTC by TarasSydor

> ### Motivate of the pull request
The motivation of this PR is RG-52 issue, which is caused by some actions not making sense on a welcome page.
As a quick solution we'll just hide entire menu bar. In the future we might want to implement more intelligent mechanism on managing views on a menu bar.

> ### Describe the technical details
As long the code hiding toolbars for the welcome page already exists, I extended it with hiding the menu bar as well.
>
> #### What does this pull request change?
Menu bar will no longer be visible when welcome page is on.
![image](https://user-images.githubusercontent.com/109239890/188470619-44dcbb8d-f98e-42a3-896a-94a12ca5ace2.png)

2022-09-05 14:28 UTC, KochynVolodymyr approved these changes

2022-09-05 14:28 UTC, KochynVolodymyr approved these changes

2022-09-06 05:26 UTC, ravic-rs commented
@TarasSydor your screenshot doesn't match the repo we are updating (text and icon).

2022-09-06 05:29 UTC, ravic-rs requested changes
Address the screenshot and add a note that it's temporary in description/title with describing reasons we discussed for doing so.

2022-09-06 11:15 UTC, TarasSydor commented
> Address the screenshot and add a note that it's temporary in description/title with describing reasons we discussed for doing so.

my bad. I copied some old resources folder. updated the screenshot according to what we have in FOEDAG.

2022-09-07 14:32 UTC, ravic-rs approved these changes

2022-09-07 14:32 UTC, merged