[RG-98]-Unsupported Design Source file formats are removed
os-fpga/FOEDAG pull request #683
Opened 2022-09-26 06:43 UTC by zaryabkhan-rs

> ### Motivate of the pull request
> - [ ] Remove unsupported design sources file format.

> ### Describe the technical details
> #### What is currently done? (Provide issue link if applicable)
Unsupported design source file formats are removed from the GUI  add source dialog.
>
> #### What does this pull request change?
![image](https://user-images.githubusercontent.com/109368108/192209953-ab1ab8d8-feb8-4b5c-a141-68d609a51e60.png)

> ### Which part of the code base require a change
> 
> - [ ] Library: <Specify the library name>
> - [ ] Plug-in: <Specify the plugin name>
> - [ ] Engine
> - [ ] Documentation
> - [ ] Regression tests
> - [ ] Continous Integration (CI) scripts

> ### Impact of the pull request

> - [ ] Require a change on Quality of Results (QoR)
> - [ ] Break back-compatibility. If so, please list who may be influenced.

2022-09-26 15:44 UTC, KochynVolodymyr approved these changes

2022-09-27 07:10 UTC, ravic-rs requested changes
Create new categories of files as defined in the ticket.

2022-09-27 07:24 UTC, zaryabkhan-rs commented
> Create new categories of files as defined in the ticket.

Modification is done
![image](https://user-images.githubusercontent.com/109368108/192460609-eb587ffe-ce58-4906-ad5f-06c81386f632.png)

2022-09-27 16:40 UTC, ravic-rs approved these changes
Looks good.

2022-09-27 16:40 UTC, merged