Fix extra # in console prompt when opening a project
os-fpga/FOEDAG pull request #749
Opened 2022-10-19 19:07 UTC by skyler-rs

> ### Motivate of the pull request
> - [ ] To address an existing issue. If so, please provide a link to the issue: <issue id>
> - [ ] Breaking new feature. If so, please describe details in the description part.
> - [x] Fix regression in gui caused by https://github.com/os-fpga/FOEDAG/pull/745

> ### Describe the technical details
> #### What is currently done? (Provide issue link if applicable)
> showPrompt() was called on the console after a project load to fix the console if any errors printed when executing tcl w/ GlobalSession->TclInterp()->evalCmd(), but if there were no errors, the the console printed two prompts indicators:
![image](https://user-images.githubusercontent.com/103447061/196781388-0f34dfa3-226a-47bc-b533-d1e581e26340.png)

>
> #### What does this pull request change?
> Switched to GlobalSession->CmdStack()->push_and_exec() which doesn't break the console on error and removed the now unnecessary showPrompt() command.

> ### Which part of the code base require a change
> 
> - [x] Library: IpConfigurator, MainWindow
> - [ ] Plug-in: <Specify the plugin name>
> - [ ] Engine
> - [ ] Documentation
> - [ ] Regression tests
> - [ ] Continous Integration (CI) scripts

> ### Testing
> - Manually tested in foedag and raptor

2022-10-21 02:17 UTC, ravic-rs requested changes
CI lines seems to be debugging.

2022-10-21 02:17 UTC, ravic-rs commented on .github/workflows/main.yml
> +      uses: hendrikmuhs/ccache-action@v1.2.3
Please remove the CI debugging lines.
For debugging it's good to create a sub-branch so changes don't make into main.

2022-10-21 16:50 UTC, TarasSydor approved these changes

2022-10-24 21:18 UTC, ravic-rs approved these changes
Looks good.

2022-10-24 21:20 UTC, merged