[RG-204] Introduced Reports tab, appearing next to the Console after running a project
os-fpga/FOEDAG pull request #834
Opened 2022-11-29 16:02 UTC by TarasSydor

> ### Motivate of the pull request
Given PR adds extra Reports tab, requested by RG-204.

> ### Describe the technical details
The tab UI is implemented as ReportsTreeWidget and is based on QTreeWidget. QTreeView was also an option, but it requires more coding and as amount of tasks or reports will not gonna change frequently, QTreeWidget is sufficient.

Next to that, ITaskReportManager API was moved from std::string to QString so as to avoid extra conversions.
>
> #### What does this pull request change?
After compilation is finished a Reports tab appears in bottom area:
![image](https://user-images.githubusercontent.com/109239890/204824865-70c28765-d25f-4c04-827e-9308c6c0e871.png)

The report gets opened after double-clicking on a leaf node. If the report is opened already, it will get selected.

One more change - actions in tasks view are only visible when the task has underlying reports. Each action corresponds to the report - functionally agreed as we don't expect more than 2 reports per task:
![image](https://user-images.githubusercontent.com/109239890/204827093-9dc25ae1-8e68-4c94-b256-6f95265d9548.png)

> ### Which part of the code base require a change
> 
> - [+] Library: <Specify the library name>
> - [ ] Plug-in: <Specify the plugin name>
> - [ ] Engine
> - [+] Documentation
> - [ ] Regression tests
> - [ ] Continous Integration (CI) scripts

2022-11-29 16:39 UTC, ravic-rs requested changes
1, Typo in "Cirtuit"
2. Look at avoiding or replacing the "Reports" in title of tab, widget, column.
3. Some conflicts from other PR merges.

2022-11-30 15:18 UTC, KochynVolodymyr approved these changes

2022-11-30 15:21 UTC, skyler-rs approved these changes

2022-11-30 18:02 UTC, ravic-rs approved these changes
Looks good. We need to handle some usecases such as an empty report/table.

2022-11-30 18:02 UTC, merged