[RG-247] Update log header logic to add header to any file w/ .rpt extension
os-fpga/FOEDAG pull request #900
Opened 2022-12-22 23:31 UTC by skyler-rs

> ### Motivate of the pull request
> - [x] To address an existing issue. If so, please provide a link to the issue: RG-247
> - [ ] Breaking new feature. If so, please describe details in the description part.

> ### Describe the technical details
> #### What is currently done? (Provide issue link if applicable)
> - We explicitly add a header to specific .rpt files that we know about during a given task
>   - As a result, unknown .rpt's created by lower level systems were missed. (See link in jira for full break down of missed files and how they were found)
>
> #### What does this pull request change?
> - We now search the project folder for any *.rpt file and add our header to it
>    - Logic has been updated to only add the header if it doesn't already exist
>    - **NOTE:** This currently is non-recursive to protect against the potential case of some sub-task that creates a large number of files in a project sub folder... Not sure if this is a valid concern, but it doesn't hurt for now.
> - Explicit commands to add a header to a given file have been removed from each sub task now that they are dynamically covered.
> - The call to add all headers has been moved into a scope guard within `Compiler::RunCompileTask`
>    - The idea here is that since the main switch case in this function directly returns the results of a call to a given task, we can't call `AddHeadersToLogs` after the task runs unless we add it in a scope guard which will fire once `RunCompileTask` has finished the requested task and then it's scope exits.
>    - By calling `AddHeaderToLogs` here, we will dynamically catch .rpt's created by any task in the switch case even if more are added down the road or sub task report file name are changed etc.

> ### Which part of the code base require a change
> 
> - [x] Library: Compiler, Utils
> - [ ] Plug-in: <Specify the plugin name>
> - [ ] Engine
> - [ ] Documentation
> - [x] Regression tests
> - [ ] Continous Integration (CI) scripts

> ### Testing
> - tests/TestGui/log_header.tcl has been updated to create a fake .rpt file before we run the analyze step and then we verify that this file gets a header added after the analyze step is run.
> - Manually tested in raptor w/ the following steps (see comment linked pr in RG-247 for full context):
>```
> build/bin/raptor --script tests/Testcases/oneff/raptor.tcl
> cd oneff_gemini
> head -n2 *.rpt
>```
>    - Used the output from the commands above to ensure that the previously missed files all have a log header now

2022-12-23 18:06 UTC, ravic-rs requested changes
There's a CI problem with test and fake.rpt seems to be missing.

2022-12-24 00:09 UTC, skyler-rs commented
> There's a CI problem with test ~and fake.rpt seems to be missing.~

I don't see any failures: https://github.com/os-fpga/FOEDAG/actions/runs/3761705044

2022-12-24 00:10 UTC, ravic-rs commented
It went away on a re-run! Seemed like it was hung on a Qt build process.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: skyler-rs ***@***.***>
Sent: Friday, December 23, 2022 4:09:23 PM
To: os-fpga/FOEDAG ***@***.***>
Cc: Ravikiran Chollangi ***@***.***>; Review requested ***@***.***>
Subject: Re: [os-fpga/FOEDAG] [RG-247] Update log header logic to add header to any file w/ .rpt extension (PR #900)


There's a CI problem with test and fake.rpt seems to be missing.

I don't see any failures: https://github.com/os-fpga/FOEDAG/actions/runs/3761705044

—
Reply to this email directly, view it on GitHub<https://github.com/os-fpga/FOEDAG/pull/900#issuecomment-1364417303>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AZ2KILZ6ZC7IGOHJV4R5TULWOY5LHANCNFSM6AAAAAATHGXANM>.
You are receiving this because your review was requested.Message ID: ***@***.***>

2022-12-27 16:30 UTC, ravic-rs approved these changes

2022-12-27 16:30 UTC, merged